name: "thanks-contributors"
description: "Collect and showcase contributors - support multiple repos or organizations"
author: "Sunrisepeak <speakshen@163.com>"

branding:
  icon: "users"
  color: "orange"

permissions:
  # For Auto Commit
  contents: write
  # For PR creation
  pull-requests: write
  # For GitHub Pages deployment
  pages: write
  id-token: write

inputs:
  targets:
    description: "Targets to scan: owner/* (all repos) or owner/repo. Leave empty to auto-detect current owner."
    required: false
    default: ""
  token:
    description: "GitHub token. Defaults to GITHUB_TOKEN if not provided. PAT recommended for large orgs."
    required: false
    default: ${{ github.token }}
  include_anonymous:
    description: "Include anonymous contributors (no login)"
    required: false
    default: "true"
  skip_archived:
    description: "Skip archived repos"
    required: false
    default: "false"
  per_repo_delay_ms:
    description: "Delay between repos to reduce rate limiting"
    required: false
    default: "150"
  output_dir:
    description: "Directory (relative to repo root) where contributors.* files are written"
    required: false
    default: ".thanks-contributors"
  auto_commit:
    description: "Automatically commit and push changes to contributors files"
    required: false
    default: "true"
  pr_branch_name:
    description: "Branch name for PR when auto_commit is false"
    required: false
    default: "thanks-contributors/update"
  pr_title:
    description: "PR title when auto_commit is false"
    required: false
    default: "chore: update contributors"
  base_branch:
    description: "Target base branch for PR (defaults to repo default branch)"
    required: false
    default: ""
  deploy_to_pages:
    description: "Deploy contributors files to GitHub Pages"
    required: false
    default: "false"
  readme_path:
    description: "Path to README file (relative to repo root) to update with contributors"
    required: false
    default: "README.md"

outputs:
  updated:
    description: "true if output file changed vs previous run (best-effort, requires checkout in caller)"
    value: ${{ steps.collect.outputs.updated }}

runs:
  using: "composite"
  steps:
    - name: Setup Python dependencies
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        if [ -f requirements.txt ]; then
          python -m pip install --quiet --upgrade pip
          python -m pip install --quiet -r requirements.txt
        fi

    - name: Collect contributors
      id: collect
      shell: bash
      env:
        TARGETS: ${{ inputs.targets }}
        GH_TOKEN: ${{ inputs.token }}
        INCLUDE_ANONYMOUS: ${{ inputs.include_anonymous }}
        SKIP_ARCHIVED: ${{ inputs.skip_archived }}
        PER_REPO_DELAY_MS: ${{ inputs.per_repo_delay_ms }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
        AUTO_COMMIT: ${{ inputs.auto_commit }}
        PR_BRANCH_NAME: ${{ inputs.pr_branch_name }}
        PR_TITLE: ${{ inputs.pr_title }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        README_PATH: ${{ inputs.readme_path }}
      run: |
        cd "${{ github.action_path }}"
        python main.py

    - name: Setup Pages
      if: ${{ inputs.deploy_to_pages == 'true' }}
      uses: actions/configure-pages@v4

    - name: Create public directory for GitHub Pages
      if: ${{ inputs.deploy_to_pages == 'true' }}
      shell: bash
      run: |
        OUTPUT_DIR="${{ inputs.output_dir }}"
        mkdir -p public
        [ -f "$OUTPUT_DIR/contributors.html" ] && cp "$OUTPUT_DIR/contributors.html" public/index.html
        [ -f "$OUTPUT_DIR/contributors.json" ] && cp "$OUTPUT_DIR/contributors.json" public/contributors.json
        [ -f "$OUTPUT_DIR/contributors.png" ] && cp "$OUTPUT_DIR/contributors.png" public/contributors.png
        ls -la public/ || echo "public directory is empty"

    - name: Upload artifact to Pages
      if: ${{ inputs.deploy_to_pages == 'true' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'public'

    - name: Deploy to GitHub Pages
      if: ${{ inputs.deploy_to_pages == 'true' }}
      id: deployment
      uses: actions/deploy-pages@v4