name: "All Contributors X"
description: "Collect contributors across public repos and generate contributors.json, contributors.html, contributors.png"
author: "Sunrisepeak <speakshen@163.com>"

branding:
  icon: "users"
  color: "orange"

inputs:
  targets:
    description: "Targets to scan: owner/* (all repos) or owner/repo. Leave empty to auto-detect current owner."
    required: false
    default: ""
  token:
    description: "GitHub token. Defaults to GITHUB_TOKEN if not provided. PAT recommended for large orgs."
    required: false
    default: ${{ github.token }}
  include_anonymous:
    description: "Include anonymous contributors (no login)"
    required: false
    default: "true"
  skip_archived:
    description: "Skip archived repos"
    required: false
    default: "false"
  per_repo_delay_ms:
    description: "Delay between repos to reduce rate limiting"
    required: false
    default: "150"
  auto_commit:
    description: "Automatically commit and push changes to contributors files"
    required: false
    default: "true"

outputs:
  updated:
    description: "true if output file changed vs previous run (best-effort, requires checkout in caller)"
    value: ${{ steps.detect.outputs.updated }}

runs:
  using: "composite"
  steps:
    - name: Setup Python dependencies
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        if [ -f requirements.txt ]; then
          python -m pip install --quiet --upgrade pip
          python -m pip install --quiet -r requirements.txt
        fi

    - name: Collect contributors
      shell: bash
      env:
        TARGETS: ${{ inputs.targets }}
        GH_TOKEN: ${{ inputs.token }}
        INCLUDE_ANONYMOUS: ${{ inputs.include_anonymous }}
        SKIP_ARCHIVED: ${{ inputs.skip_archived }}
        PER_REPO_DELAY_MS: ${{ inputs.per_repo_delay_ms }}
      run: |
        cd "${{ github.action_path }}"
        python main.py

    - name: Detect changes (best-effort)
      id: detect
      shell: bash
      run: |
        if git status --porcelain -- contributors.json contributors.png contributors.html | grep .; then
          echo "updated=true" >> "$GITHUB_OUTPUT"
        else
          echo "updated=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Auto-commit changes
      if: inputs.auto_commit == 'true' && steps.detect.outputs.updated == 'true'
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add contributors.json contributors.png contributors.html
        git commit -m "chore: update contributors"
        git push